from app.agents.definitions import AGENTS
from app.domain.models import Classification, Proposal, now
from app.engineering_tools.calculations import q


def validate(model, proposal: Proposal):
    if proposal.target_revision != model.revision:
        raise ValueError("Stale target revision")
    if (
        proposal.agent not in AGENTS
        or proposal.agent_version != AGENTS[proposal.agent].prompt_version
    ):
        raise ValueError("Unknown agent or version")
    if proposal.agent == "review":
        raise ValueError("Independent review submits findings, never model proposals")
    ids = [op.entity.id for op in proposal.operations]
    if len(set(ids)) != len(ids):
        raise ValueError("Duplicate or conflicting operations")
    targets = set(model.entities) | set(ids)
    for ref in proposal.evidence_references + proposal.assumptions:
        if ref not in model.entities:
            raise ValueError("Missing evidence or assumption reference")
    for op in proposal.operations:
        e = op.entity
        if e.kind not in AGENTS[proposal.agent].authority or e.owner != proposal.agent:
            raise ValueError("Agent lacks authority for object or owner")
        if op.action == "add" and e.id in model.entities:
            raise ValueError("Object already exists")
        if op.action == "replace" and e.id not in model.entities:
            raise ValueError("Cannot replace nonexistent object")
        if e.id in model.entities and model.entities[e.id].kind != e.kind:
            raise ValueError("Entity type is immutable")
        if any(r.target not in targets for r in e.relations):
            raise ValueError("Dangling traceability relationship")
        if len({(r.type, r.target) for r in e.relations}) != len(e.relations):
            raise ValueError("Duplicate relationship")
        if e.kind == "Requirement" and not any(r.type == "derives_from" for r in e.relations):
            raise ValueError("Requirement must trace to an objective or parent requirement")
        if e.classification == Classification.CALCULATION:
            raise ValueError("Calculated conclusions must be generated by the tool service")
        if e.classification == Classification.HUMAN:
            raise ValueError("Agents cannot impersonate human decisions")
        if e.classification == Classification.FACT and not any(
            r.type == "evidenced_by"
            and r.target in model.entities
            and model.entities[r.target].kind == "Evidence"
            for r in e.relations
        ):
            raise ValueError("Sourced facts require existing evidence")
        if e.kind == "Parameter":
            q(e.data["quantity"], e.data["dimension"])


def accept(model, proposal):
    validate(model, proposal)
    changed = {op.entity.id for op in proposal.operations if op.action == "replace"}
    for op in proposal.operations:
        e = op.entity.model_copy(deep=True)
        e.state = "accepted"
        e.revision = model.revision + 1
        e.modified_at = now()
        if e.id in model.entities:
            e.created_at = model.entities[e.id].created_at
        model.entities[e.id] = e
    # Transitive dependency invalidation; historical snapshots retain the previous states.
    visited = set(changed)
    while changed:
        downstream = {
            e.id
            for e in model.entities.values()
            if e.id not in visited and any(r.target in changed for r in e.relations)
        }
        for key in downstream:
            model.entities[key].state = "stale"
            model.entities[key].revision = model.revision + 1
            model.entities[key].modified_at = now()
        visited |= downstream
        changed = downstream
    proposal.status = "accepted"
