from app.agents.definitions import AGENTS
from app.domain.engineering_inputs import validate_inputs
from app.domain.interfaces import DataContract
from app.domain.models import Classification, Proposal, now
from app.domain.requirement_checks import Criterion
from app.engineering_tools.calculations import q


def validate(model, proposal: Proposal):
    if proposal.target_revision != model.revision:
        raise ValueError("Stale target revision")
    human = proposal.agent == "human"
    if not human and (
        proposal.agent not in AGENTS
        or proposal.agent_version != AGENTS[proposal.agent].prompt_version
    ):
        raise ValueError("Unknown agent or version")
    if proposal.agent == "review":
        raise ValueError("Independent review submits findings, never model proposals")
    ids = [op.entity.id for op in proposal.operations]
    if len(set(ids)) != len(ids):
        raise ValueError("Duplicate or conflicting operations")
    targets = set(model.entities) | set(ids)
    for ref in proposal.evidence_references + proposal.assumptions:
        if ref not in model.entities:
            raise ValueError("Missing evidence or assumption reference")
    for op in proposal.operations:
        e = op.entity
        allowed = (
            ["Assumption", "Requirement", "Parameter", "Interface"]
            if human
            else AGENTS[proposal.agent].authority
        )
        if e.kind not in allowed or e.owner != proposal.agent:
            raise ValueError("Agent lacks authority for object or owner")
        if human and (op.action != "replace" or proposal.proposal_type != "design change"):
            raise ValueError("Human proposals may only edit existing design inputs")
        if op.action == "add" and e.id in model.entities:
            raise ValueError("Object already exists")
        if op.action == "replace" and e.id not in model.entities:
            raise ValueError("Cannot replace nonexistent object")
        if e.id in model.entities and model.entities[e.id].kind != e.kind:
            raise ValueError("Entity type is immutable")
        if any(r.target not in targets for r in e.relations):
            raise ValueError("Dangling traceability relationship")
        if len({(r.type, r.target) for r in e.relations}) != len(e.relations):
            raise ValueError("Duplicate relationship")
        if e.kind == "Requirement" and not any(r.type == "derives_from" for r in e.relations):
            raise ValueError("Requirement must trace to an objective or parent requirement")
        if e.kind == "Requirement" and e.data.get("criterion") is not None:
            Criterion.model_validate(e.data["criterion"])
        if e.kind == "Interface" and e.data.get("data_contract") is not None:
            DataContract.model_validate(e.data["data_contract"])
        if e.classification == Classification.CALCULATION:
            raise ValueError("Calculated conclusions must be generated by the tool service")
        if e.classification == Classification.HUMAN:
            raise ValueError("Agents cannot impersonate human decisions")
        if e.classification == Classification.FACT and not any(
            r.type == "evidenced_by"
            and r.target in model.entities
            and model.entities[r.target].kind == "Evidence"
            for r in e.relations
        ):
            raise ValueError("Sourced facts require existing evidence")
        if e.kind == "Parameter":
            if "inputs" in e.data:
                validate_inputs(e.data["tool"], e.data["inputs"])
                if op.action == "replace":
                    prior = model.entities[e.id]
                    if any(e.data.get(k) != prior.data.get(k) for k in ["tool", "candidate"]):
                        raise ValueError("Parameter tool and candidate are immutable")
            else:
                q(e.data["quantity"], e.data["dimension"])


def accept(model, proposal):
    validate(model, proposal)
    changed = {op.entity.id for op in proposal.operations if op.action == "replace"}
    for op in proposal.operations:
        e = op.entity.model_copy(deep=True)
        e.state = "accepted"
        e.revision = model.revision + 1
        e.modified_at = now()
        if e.id in model.entities:
            e.created_at = model.entities[e.id].created_at
        model.entities[e.id] = e
    invalidate_dependents(model, changed)
    proposal.status = "accepted"


def invalidate_dependents(model, changed):
    # Transitive dependency invalidation; historical snapshots retain the previous states.
    visited = set(changed)
    while changed:
        downstream = {
            e.id
            for e in model.entities.values()
            if e.id not in visited
            and e.kind not in ["Baseline", "AgentRun", "AgentDefinition"]
            and e.state != "superseded"
            and any(r.target in changed for r in e.relations)
        }
        for key in downstream:
            model.entities[key].state = "stale"
            if (
                model.entities[key].data.get("requirement")
                or model.entities[key].data.get("check_type") == "interface_consistency"
            ) and model.entities[key].kind == "VerificationItem":
                model.entities[key].data["status"] = "stale"
            model.entities[key].revision = model.revision + 1
            model.entities[key].modified_at = now()
        visited |= downstream
        changed = downstream
